envs: ['lcl', 'prd', 'tst']

prd:
  db:
    host: 'database'
    port: '5432'
    user: 'xxxx'
    pass: 'xxxx'
    engine: 'postgresql'
    db: 'default'
lcl:
  db:
    host: 'database'
    port: '5432'
    user: 'root'
    pass: 'root'
    engine: 'postgresql'
    db: 'default'
tst:
  # nothing yet