prd:
  db:
    host: 'database'
    port: '5432'
    user: 'xxxx'
    pass: 'xxxx'
    engine: 'postgresql'
    db: 'default'
  cert-service:
    host: 'cert-service'
    port: 8080
lcl:
  db:
    host: 'database'
    port: '5432'
    user: 'root'
    pass: 'root'
    engine: 'postgresql'
    db: 'default'
  cert-service:
    host: 'cert-service'
    port: 8080