version: '3'

services:
  api:
    build: ./
    ports:
      - 9000:9000
    environment:
      env: 'lcl'
    volumes:
      - .:/opt/app
    depends_on:
      - database
      - cert-service
      - cache
  api-test:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      env: 'tst'
    command: pytest tests
    volumes:
      - .:/opt/app
    depends_on:
      - cert-service
      - cache
  database:
    image: postgres:10.4
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: default
    ports:
      - 5432:5432
  cert-service:
    image: kennethreitz/httpbin
    ports:
      - 8080:80
  cache:
    image: redis:4.0.10
    ports:
      - 6379:6379
