version: '3'

services:
  api:
    build: ./
    ports:
      - 9000:9000
    volumes:
      - .:/opt/app
  api-test:
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: pytest
    command: tests
    volumes:
      - .:/opt/app