version: '3'

services:
  api:
    build: ./
    ports:
      - 9000:9000
    environment:
      env: 'local'
    volumes:
      - .:/opt/app
  api-test:
    build:
      context: ./
      dockerfile: Dockerfile
    command: pytest tests
    volumes:
      - .:/opt/app
  database:
    image: postgres:10.6