openapi: 3.0.0
info:
  title: Customer Certificates
  description: Manage user certificates
  version: 1.0.0
servers:
  - url: http://api.example.com
    description: Production server
paths:
  /users:
    post:
      summary: Create a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPost'
      responses:
        '201':
          description: User was successfully created
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 4
        '400':
          description: One or more specified user properties are invalid
        '409':
          description: A user with the specified email already exists
        '500':
          description: Internal server error
  /users/{user_id}:
    parameters:
      - name: user_id
        in: path
        required: true
        description: The id of the user resource
        schema:
          type: integer
          format: int64
          minimum: 1
    get:
      summary: Get a user
      responses:
        '200':
          description: User successfully found
        '404':
          description: User not found
        '500':
          description: Internal server error
    delete:
      summary: Delete a user
      responses:
        '204':
          description: User successfully deleted
        '404':
          description: User not found
        '500':
          description: Internal server error
  /users/{user_id}/certificates:
    parameters:
      - name: user_id
        in: path
        required: true
        description: The id of the user
        schema:
          type: integer
          format: int64
          minimum: 1
    post:
      summary: Create a certificate for a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CertificatePost'
      responses:
        '201':
          description: Certificate was successfully created for user
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 1
        '400':
          description: One or more specified certificate properties are invalid
        '404':
          description: User not found
        '500':
          description: Internal server error
    get:
      summary: List certificates for a user
      parameters:
        - in: query
          name: active
          schema:
            type: string
          description: Return only active certificates if set to 'true' otherwise all certificates
      responses:
        '200':
          description: Certificates successfully found
        '404':
          description: User not found
        '500':
          description: Internal server error
  /users/{user_id}/certificates/{certificate_id}:
    parameters:
      - name: user_id
        in: path
        required: true
        description: The id of the user
        schema:
          type: integer
          format: int64
          minimum: 1
      - name: certificate_id
        in: path
        required: true
        description: The id of the certificate
        schema:
          type: integer
          format: int64
          minimum: 1
    patch:
      summary: Update a certificate for a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CertificatePatch'
      responses:
        '202':
          description: Certificate was successfully updated for user, but has to notify external system
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 1
        '400':
          description: One or more specified certificate properties are invalid
        '404':
          description: User or certificate not found
        '500':
          description: Internal server error
components:
  schemas:
    UserPost:
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
    CertificatePost:
      properties:
        private_key:
          type: string
        active:
          type: boolean
        body:
          type: string
    CertificatePatch:
      properties:
        active:
          type: boolean
        notify:
          type: boolean