openapi: 3.0.0
info:
  title: Customer Certificates
  description: Manage user certificates
  contact: andrew@alawson.io
  version: 1.0.0
servers:
  - url: http://api.example.com
    description: Production server