"""Added delete cascade

Revision ID: 17a5465d870d
Revises: 66762ce556d5
Create Date: 2018-07-31 04:36:05.808048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17a5465d870d'
down_revision = '66762ce556d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('certificates_user_id_fkey', 'certificates', type_='foreignkey')
    op.create_foreign_key(None, 'certificates', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'certificates', type_='foreignkey')
    op.create_foreign_key('certificates_user_id_fkey', 'certificates', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
