"""add composite index

Revision ID: 28da97b98ec6
Revises: 9a797533bfb0
Create Date: 2018-08-01 03:32:08.866356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28da97b98ec6'
down_revision = '9a797533bfb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_id_and_id_index', 'certificates', ['user_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_id_and_id_index', table_name='certificates')
    # ### end Alembic commands ###
