"""Added foreign keys and nullable

Revision ID: 66762ce556d5
Revises: a19d16df687c
Create Date: 2018-07-31 03:38:44.342802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66762ce556d5'
down_revision = 'a19d16df687c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificates', 'active',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('certificates', 'body',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('certificates', 'private_key',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.alter_column('certificates', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'certificates', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'certificates', type_='foreignkey')
    op.alter_column('certificates', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('certificates', 'private_key',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.alter_column('certificates', 'body',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('certificates', 'active',
               existing_type=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###
