"""use binary type for cert body

Revision ID: 82714de7bd1f
Revises: ccf25419dd1d
Create Date: 2018-07-29 19:28:39.969338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82714de7bd1f'
down_revision = 'ccf25419dd1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificates', 'body',
               existing_type=sa.VARCHAR(),
               type_=sa.LargeBinary(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificates', 'body',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
